require('dotenv').config?.();
const path=require('path'); const fs=require('fs'); const crypto=require('crypto'); const express=require('express'); const session=require('express-session'); const helmet=require('helmet'); const compression=require('compression'); const rateLimit=require('express-rate-limit'); const flash=require('connect-flash'); const bcrypt=require('bcryptjs'); const speakeasy=require('speakeasy'); const QRCode=require('qrcode'); const multer=require('multer');
const JsonStore=require('./src/store'); const makeSeed=require('./src/seed'); const {money,slug,uid,absolute,stripHtml}=require('./src/helpers');

(async()=>{
const app=express(); const PORT=Number(process.env.PORT||8080); const DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data'); const UPLOAD_DIR=process.env.UPLOAD_DIR||path.join(__dirname,'uploads'); const SESSION_DIR=process.env.SESSION_DIR||path.join(DATA_DIR,'sessions'); const BASE_URL=(process.env.BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,''); fs.mkdirSync(DATA_DIR,{recursive:true}); fs.mkdirSync(UPLOAD_DIR,{recursive:true}); fs.mkdirSync(SESSION_DIR,{recursive:true});

class PersistentSessionStore extends session.Store{
  constructor(dir){super();this.dir=dir;fs.mkdirSync(dir,{recursive:true});}
  file(sid){return path.join(this.dir,crypto.createHash('sha256').update(String(sid)).digest('hex')+'.json');}
  get(sid,cb){fs.readFile(this.file(sid),'utf8',(err,text)=>{if(err)return cb(err.code==='ENOENT'?null:err,null);try{const value=JSON.parse(text);const expires=value?.cookie?.expires?new Date(value.cookie.expires).getTime():0;if(expires&&expires<Date.now()){return this.destroy(sid,()=>cb(null,null));}cb(null,value);}catch(e){cb(e);}});}
  set(sid,value,cb){const file=this.file(sid),tmp=file+'.tmp';fs.writeFile(tmp,JSON.stringify(value),err=>{if(err)return cb&&cb(err);fs.rename(tmp,file,e=>cb&&cb(e));});}
  destroy(sid,cb){fs.unlink(this.file(sid),err=>cb&&cb(err&&err.code!=='ENOENT'?err:null));}
  touch(sid,value,cb){this.set(sid,value,cb);}
}
const seed=await makeSeed(process.env.ADMIN_ID||'admin',process.env.ADMIN_PASSWORD||'TemanBelanja@2026'); const store=new JsonStore(path.join(DATA_DIR,'db.json'),()=>seed);
app.set('view engine','ejs'); app.set('views',path.join(__dirname,'views')); app.set('trust proxy',true);
app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:false})); app.use(compression()); app.use(express.urlencoded({extended:true,limit:'2mb'})); app.use(express.json({limit:'2mb'})); app.use('/assets',express.static(path.join(__dirname,'public'),{maxAge:'7d'})); app.use('/uploads',express.static(UPLOAD_DIR,{maxAge:'30d'}));
app.use(session({name:'tb.sid',store:new PersistentSessionStore(SESSION_DIR),secret:process.env.SESSION_SECRET||'dev-change-this-secret-before-production-12345',proxy:true,resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,sameSite:'lax',secure:'auto',maxAge:60*60*1000}})); app.use(flash());
app.use((req,res,next)=>{const db=store.read(); res.locals.settings=db.settings; res.locals.money=money; res.locals.currentUser=req.session.user||null; res.locals.flash={success:req.flash('success'),error:req.flash('error')}; res.locals.baseUrl=BASE_URL; res.locals.path=req.path; next();});
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:true,legacyHeaders:false,message:'Terlalu banyak percobaan login. Coba lagi nanti.'});
const auth=(req,res,next)=>req.session.user?next():res.redirect('/admin/login');
const isUnsafeMethod=req=>['POST','PUT','PATCH','DELETE'].includes(req.method);
const csrfTokenFrom=req=>String((req.body&&req.body._csrf)||req.get('x-csrf-token')||'');
const safeEqual=(a,b)=>{const x=Buffer.from(String(a||''));const y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y)};
const verifyCsrf=(req,res,next)=>{if(!safeEqual(csrfTokenFrom(req),req.session.csrf))return res.status(403).send('CSRF token tidak valid. Silakan buka ulang halaman login admin lalu coba lagi.');next();};
const csrf=(req,res,next)=>{if(!req.session.csrf)req.session.csrf=uid();res.locals.csrf=req.session.csrf;const multipart=req.is('multipart/form-data');if(isUnsafeMethod(req)&&!multipart)return verifyCsrf(req,res,next);next();};
app.use(csrf);
const upload=multer({storage:multer.diskStorage({destination:UPLOAD_DIR,filename:(req,file,cb)=>cb(null,`${Date.now()}-${uid().slice(0,8)}${path.extname(file.originalname).toLowerCase()}`)}),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp','image/gif'].includes(file.mimetype))});
function seo(res,data={}){return {title:data.title||res.locals.settings.siteName,description:data.description||res.locals.settings.siteDescription,canonical:absolute(BASE_URL,data.canonical||'/'),image:data.image||absolute(BASE_URL,'/assets/img/og-default.svg'),type:data.type||'website',jsonLd:data.jsonLd||null}}
app.get('/health',(req,res)=>res.json({status:'ok',service:'teman-belanja',time:new Date().toISOString()}));
app.get('/',(req,res)=>{const db=store.read();res.render('home',{seo:seo(res,{title:`${db.settings.siteName} — ${db.settings.tagline}`}),categories:db.categories,featured:db.products.filter(x=>x.isActive&&x.isFeatured).slice(0,10),latest:db.products.filter(x=>x.isActive).slice(-8).reverse(),articles:db.articles.filter(x=>x.isPublished).slice(-4).reverse()});});
app.get('/cari',(req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();const db=store.read();const products=db.products.filter(x=>x.isActive&&(!q||`${x.name} ${x.shortDescription} ${x.category}`.toLowerCase().includes(q)));res.render('listing',{seo:seo(res,{title:`Hasil pencarian ${q||'produk'} | ${db.settings.siteName}`,canonical:`/cari?q=${encodeURIComponent(q)}`}),title:q?`Hasil pencarian: ${q}`:'Semua Produk',products,categories:db.categories,q});});
app.get('/kategori/:slug',(req,res,next)=>{const db=store.read();const cat=db.categories.find(x=>x.slug===req.params.slug);if(!cat)return next();const products=db.products.filter(x=>x.isActive&&x.category===cat.slug);res.render('listing',{seo:seo(res,{title:`${cat.name} | ${db.settings.siteName}`,description:`Rekomendasi produk ${cat.name} pilihan di ${db.settings.siteName}.`,canonical:`/kategori/${cat.slug}`}),title:cat.name,products,categories:db.categories,q:''});});
app.get('/produk/:slug',(req,res,next)=>{const db=store.read();const p=db.products.find(x=>x.slug===req.params.slug&&x.isActive);if(!p)return next();const related=db.products.filter(x=>x.isActive&&x.category===p.category&&x.id!==p.id).slice(0,5);const jsonLd={"@context":"https://schema.org","@type":"Product",name:p.name,image:p.images,description:stripHtml(p.description),offers:{"@type":"Offer",priceCurrency:'IDR',price:p.price,availability:'https://schema.org/InStock',url:absolute(BASE_URL,`/produk/${p.slug}`)},aggregateRating:{"@type":"AggregateRating",ratingValue:p.rating||4.8,reviewCount:Math.max(1,p.clicks||1)}};res.render('product',{seo:seo(res,{title:`${p.name} | ${db.settings.siteName}`,description:p.shortDescription,canonical:`/produk/${p.slug}`,image:(p.images&&p.images[0])||absolute(BASE_URL,'/assets/img/og-default.svg'),type:'product',jsonLd}),p,related,categories:db.categories});});
app.get('/go/:id',async(req,res)=>{const db=store.read();const p=db.products.find(x=>x.id===req.params.id&&x.isActive);if(!p)return res.redirect('/');await store.mutate(d=>{const x=d.products.find(v=>v.id===p.id);x.clicks=(x.clicks||0)+1;d.clicks.push({id:uid(),productId:p.id,at:new Date().toISOString(),ref:req.get('referer')||'',ua:req.get('user-agent')||'',ip:req.ip});if(d.clicks.length>50000)d.clicks=d.clicks.slice(-50000);});res.redirect(p.affiliateUrl);});
app.get('/artikel',(req,res)=>{const db=store.read();const articles=db.articles.filter(x=>x.isPublished).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));res.render('articles',{seo:seo(res,{title:`Artikel & Review | ${db.settings.siteName}`,canonical:'/artikel'}),articles});});
app.get('/artikel/:slug',(req,res,next)=>{const db=store.read();const a=db.articles.find(x=>x.slug===req.params.slug&&x.isPublished);if(!a)return next();res.render('article',{seo:seo(res,{title:`${a.title} | ${db.settings.siteName}`,description:a.excerpt,canonical:`/artikel/${a.slug}`,image:a.cover,type:'article'}),a,latest:db.articles.filter(x=>x.isPublished&&x.id!==a.id).slice(-5).reverse()});});
app.get('/tentang',(req,res)=>res.render('static',{seo:seo(res,{title:`Tentang Kami | ${res.locals.settings.siteName}`,canonical:'/tentang'}),title:'Tentang TEMAN BELANJA',content:'Kami membantu pengunjung menemukan produk yang relevan melalui rekomendasi, perbandingan, dan informasi yang mudah dipahami.'}));
app.get('/kebijakan-privasi',(req,res)=>res.render('static',{seo:seo(res,{title:`Kebijakan Privasi | ${res.locals.settings.siteName}`,canonical:'/kebijakan-privasi'}),title:'Kebijakan Privasi',content:'Kami hanya menyimpan data teknis seperlunya untuk keamanan, statistik klik, dan peningkatan layanan. Kami tidak menjual data pribadi pengunjung.'}));
app.get('/disclaimer',(req,res)=>res.render('static',{seo:seo(res,{title:`Disclaimer Affiliate | ${res.locals.settings.siteName}`,canonical:'/disclaimer'}),title:'Disclaimer Affiliate',content:res.locals.settings.affiliateDisclosure}));
app.get('/robots.txt',(req,res)=>res.type('text/plain').send(`User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ${BASE_URL}/sitemap.xml\n`));
app.get('/sitemap.xml',(req,res)=>{const db=store.read();const urls=['/','/artikel','/tentang','/kebijakan-privasi','/disclaimer',...db.categories.map(x=>`/kategori/${x.slug}`),...db.products.filter(x=>x.isActive).map(x=>`/produk/${x.slug}`),...db.articles.filter(x=>x.isPublished).map(x=>`/artikel/${x.slug}`)];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${absolute(BASE_URL,u)}</loc></url>`).join('')}</urlset>`)});
app.get('/rss.xml',(req,res)=>{const db=store.read();res.type('application/rss+xml').send(`<?xml version="1.0"?><rss version="2.0"><channel><title>${db.settings.siteName}</title><link>${BASE_URL}</link><description>${db.settings.siteDescription}</description>${db.articles.filter(x=>x.isPublished).map(a=>`<item><title><![CDATA[${a.title}]]></title><link>${absolute(BASE_URL,`/artikel/${a.slug}`)}</link><description><![CDATA[${a.excerpt}]]></description></item>`).join('')}</channel></rss>`)});

app.get('/admin/login',(req,res,next)=>{if(req.session.user)return res.redirect('/admin');res.set('Cache-Control','no-store, no-cache, must-revalidate, private');req.session.save(err=>{if(err)return next(err);res.render('admin/login',{layout:false,csrf:req.session.csrf});});});
app.post('/admin/login',loginLimiter,async(req,res)=>{const db=store.read();const user=db.users.find(x=>x.username===String(req.body.username||''));if(!user||!await bcrypt.compare(String(req.body.password||''),user.passwordHash)){req.flash('error','ID atau password salah.');return res.redirect('/admin/login');}req.session.pendingUser=user.id;if(user.twoFactorEnabled)return res.redirect('/admin/2fa');req.session.user={id:user.id,username:user.username,role:user.role};await store.mutate(d=>{d.users.find(x=>x.id===user.id).lastLogin=new Date().toISOString();});res.redirect('/admin/setup-2fa');});
app.get('/admin/2fa',(req,res)=>req.session.pendingUser?res.render('admin/verify',{csrf:req.session.csrf}):res.redirect('/admin/login'));
app.post('/admin/2fa',async(req,res)=>{const db=store.read();const user=db.users.find(x=>x.id===req.session.pendingUser);const ok=user&&speakeasy.totp.verify({secret:user.twoFactorSecret,encoding:'base32',token:String(req.body.token||'').replace(/\s/g,''),window:1});if(!ok){req.flash('error','Kode 2FA tidak valid.');return res.redirect('/admin/2fa');}req.session.user={id:user.id,username:user.username,role:user.role};delete req.session.pendingUser;await store.mutate(d=>{d.users.find(x=>x.id===user.id).lastLogin=new Date().toISOString();});res.redirect('/admin');});
app.get('/admin/setup-2fa',auth,async(req,res)=>{const db=store.read();const user=db.users.find(x=>x.id===req.session.user.id);if(user.twoFactorEnabled)return res.redirect('/admin');if(!req.session.setupSecret)req.session.setupSecret=speakeasy.generateSecret({name:`TEMAN BELANJA (${user.username})`,length:20}).base32;const otpauth=speakeasy.otpauthURL({secret:req.session.setupSecret,label:`TEMAN BELANJA:${user.username}`,issuer:'TEMAN BELANJA',encoding:'base32'});res.render('admin/setup2fa',{qr:await QRCode.toDataURL(otpauth),secret:req.session.setupSecret,csrf:req.session.csrf});});
app.post('/admin/setup-2fa',auth,async(req,res)=>{const secret=req.session.setupSecret;const ok=secret&&speakeasy.totp.verify({secret,encoding:'base32',token:String(req.body.token||''),window:1});if(!ok){req.flash('error','Kode tidak valid.');return res.redirect('/admin/setup-2fa');}await store.mutate(d=>{const u=d.users.find(x=>x.id===req.session.user.id);u.twoFactorSecret=secret;u.twoFactorEnabled=true;d.audit.push({id:uid(),user:u.username,action:'Mengaktifkan 2FA',at:new Date().toISOString()});});delete req.session.setupSecret;req.flash('success','2FA berhasil diaktifkan.');res.redirect('/admin');});
app.post('/admin/logout',auth,(req,res)=>req.session.destroy(()=>res.redirect('/admin/login')));
app.get('/admin',auth,(req,res)=>{const db=store.read();const last7=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=d.toISOString().slice(0,10);return {date:key,count:db.clicks.filter(x=>x.at.startsWith(key)).length}});res.render('admin/dashboard',{db,last7});});
app.get('/admin/products',auth,(req,res)=>{const db=store.read();res.render('admin/products',{products:db.products,categories:db.categories});});
app.get('/admin/products/new',auth,(req,res)=>{const db=store.read();res.render('admin/product-form',{p:null,categories:db.categories});});
app.get('/admin/products/:id/edit',auth,(req,res,next)=>{const db=store.read();const p=db.products.find(x=>x.id===req.params.id);if(!p)return next();res.render('admin/product-form',{p,categories:db.categories});});
app.post('/admin/products/save',auth,upload.array('images',8),verifyCsrf,async(req,res)=>{const b=req.body;const name=String(b.name||'').trim();const affiliateUrl=String(b.affiliateUrl||'').trim();if(!name||!affiliateUrl){req.flash('error','Nama produk dan link affiliate wajib diisi.');return res.redirect(b.id?`/admin/products/${b.id}/edit`:'/admin/products/new');}const newUrls=String(b.imageUrls||'').split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);const invalidUrl=newUrls.find(x=>!/^https?:\/\//i.test(x));if(invalidUrl){req.flash('error',`Link foto tidak valid: ${invalidUrl}`);return res.redirect(b.id?`/admin/products/${b.id}/edit`:'/admin/products/new');}await store.mutate(d=>{let p=b.id?d.products.find(x=>x.id===b.id):null;const remove=new Set(Array.isArray(b.removeImages)?b.removeImages:(b.removeImages?[b.removeImages]:[]));const kept=(p?.images||[]).filter(x=>!remove.has(x));const uploaded=(req.files||[]).map(f=>`/uploads/${f.filename}`);const images=[...new Set([...kept,...newUrls,...uploaded])].slice(0,12);const obj={id:p?.id||uid(),name,slug:slug(b.slug||name),category:b.category,price:Math.max(0,Number(b.price||0)),oldPrice:Math.max(0,Number(b.oldPrice||0)),marketplace:String(b.marketplace||'Shopee').trim(),affiliateUrl,images:images.length?images:['/assets/img/og-default.svg'],shortDescription:String(b.shortDescription||'').trim(),description:String(b.description||'').trim(),advantages:String(b.advantages||'').split('\n').map(x=>x.trim()).filter(Boolean),suitableFor:String(b.suitableFor||'').split('\n').map(x=>x.trim()).filter(Boolean),usage:String(b.usage||'').trim(),rating:Math.min(5,Math.max(1,Number(b.rating||4.8))),soldLabel:String(b.soldLabel||'').trim(),isFeatured:b.isFeatured==='on',isActive:b.isActive==='on',clicks:p?.clicks||0,createdAt:p?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(p)Object.assign(p,obj);else d.products.unshift(obj);d.audit.push({id:uid(),user:req.session.user.username,action:`Simpan produk: ${obj.name}`,at:new Date().toISOString()});});req.flash('success','Produk berhasil disimpan. Nama, harga, dan seluruh foto sudah tampil pada katalog.');res.redirect('/admin/products');});
app.post('/admin/products/:id/delete',auth,async(req,res)=>{await store.mutate(d=>{d.products=d.products.filter(x=>x.id!==req.params.id)});req.flash('success','Produk dihapus.');res.redirect('/admin/products');});
app.get('/admin/categories',auth,(req,res)=>{const db=store.read();res.render('admin/categories',{categories:db.categories});});
app.post('/admin/categories/save',auth,async(req,res)=>{await store.mutate(d=>{const obj={id:req.body.id||uid(),name:req.body.name,slug:slug(req.body.slug||req.body.name),icon:req.body.icon||'🛍️'};const x=d.categories.find(v=>v.id===obj.id);x?Object.assign(x,obj):d.categories.push(obj)});req.flash('success','Kategori disimpan.');res.redirect('/admin/categories');});
app.post('/admin/categories/:id/delete',auth,async(req,res)=>{await store.mutate(d=>{d.categories=d.categories.filter(x=>x.id!==req.params.id)});res.redirect('/admin/categories');});
app.get('/admin/articles',auth,(req,res)=>{const db=store.read();res.render('admin/articles',{articles:db.articles});});
app.get('/admin/articles/new',auth,(req,res)=>res.render('admin/article-form',{a:null}));
app.get('/admin/articles/:id/edit',auth,(req,res,next)=>{const a=store.read().articles.find(x=>x.id===req.params.id);if(!a)return next();res.render('admin/article-form',{a});});
app.post('/admin/articles/save',auth,upload.single('coverFile'),verifyCsrf,async(req,res)=>{const b=req.body;await store.mutate(d=>{let a=b.id?d.articles.find(x=>x.id===b.id):null;const obj={id:a?.id||uid(),title:b.title,slug:slug(b.slug||b.title),excerpt:b.excerpt,content:b.content,cover:req.file?`/uploads/${req.file.filename}`:b.cover||a?.cover||'',category:b.category||'Tips Belanja',isPublished:b.isPublished==='on',publishedAt:b.publishedAt?new Date(b.publishedAt).toISOString():a?.publishedAt||new Date().toISOString(),createdAt:a?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};a?Object.assign(a,obj):d.articles.unshift(obj)});req.flash('success','Artikel disimpan.');res.redirect('/admin/articles');});
app.post('/admin/articles/:id/delete',auth,async(req,res)=>{await store.mutate(d=>{d.articles=d.articles.filter(x=>x.id!==req.params.id)});res.redirect('/admin/articles');});
app.get('/admin/settings',auth,(req,res)=>res.render('admin/settings',{s:store.read().settings}));
app.post('/admin/settings',auth,async(req,res)=>{await store.mutate(d=>Object.assign(d.settings,req.body));req.flash('success','Pengaturan disimpan.');res.redirect('/admin/settings');});
app.get('/admin/security',auth,(req,res)=>res.render('admin/security'));
app.post('/admin/security/password',auth,async(req,res)=>{const db=store.read();const u=db.users.find(x=>x.id===req.session.user.id);if(!await bcrypt.compare(req.body.currentPassword,u.passwordHash)||String(req.body.newPassword||'').length<10){req.flash('error','Password lama salah atau password baru kurang dari 10 karakter.');return res.redirect('/admin/security')}await store.mutate(async d=>{d.users.find(x=>x.id===u.id).passwordHash=await bcrypt.hash(req.body.newPassword,12)});req.flash('success','Password berhasil diubah.');res.redirect('/admin/security');});
app.use((req,res)=>res.status(404).render('404',{seo:seo(res,{title:'Halaman Tidak Ditemukan'})})); app.use((err,req,res,next)=>{console.error(err);res.status(500).render('500',{seo:seo(res,{title:'Terjadi Kesalahan'}),message:process.env.NODE_ENV==='production'?'Terjadi kesalahan pada server.':err.message})});
app.listen(PORT,'0.0.0.0',()=>console.log(`TEMAN BELANJA running on port ${PORT}`));
})();
